# Generated by Django 3.1.4 on 2020-12-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20201221_0055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='tags',
            new_name='tag',
        ),
    ]
