# Generated by Django 3.1.4 on 2020-12-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20201221_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tag',
            field=models.ManyToManyField(blank=True, to='rooms.Tag'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
