# Generated by Django 3.1.4 on 2020-12-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20201223_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tag',
            field=models.ManyToManyField(blank=True, to='rooms.Tag'),
        ),
    ]
