# Generated by Django 3.1.4 on 2020-12-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20201223_2338'),
        ('wish_lists', '0003_auto_20201223_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='wish_lists', to='rooms.Room'),
        ),
    ]
